# Generated by Django 3.0.6 on 2021-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapest_trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
