# Generated by Django 3.0.6 on 2021-06-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapest_trip', '0002_arrivalcity_departurecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsdata',
            name='arrival_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightsdata',
            name='departure_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
