# Generated by Django 3.0.6 on 2021-06-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapest_trip', '0005_auto_20210606_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsdata',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightsdata',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightsdata',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightsdata',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
