# Generated by Django 3.0.6 on 2021-06-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapest_trip', '0006_auto_20210606_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, choices=[('Played', 'Played'), ('Paused', 'Paused')], max_length=200, null=True)),
            ],
        ),
    ]
